# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_finder',
            name='experience',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
